"""Generate app/services/_personal_writings_seed_data.py from the owner's Word
documents (spiritual autobiography ×3 files + the worldly/hereafter goals doc).

Merge contract (owner's rule): content may be dropped ONLY when an exact
duplicate exists. Two of the three autobiography .doc files are byte-identical;
the third is an older revision. The merged document = newest revision verbatim
+ an appendix holding every older-revision block whose exact text is absent
from the newest. A machine gate verifies that EVERY sentence of BOTH revisions
appears verbatim (whitespace-normalised) in the merged body — generation fails
otherwise. The goals .docx is stored whole (single writing, order preserved).

Usage:
    python scripts/generate_writings_seed.py <v59.txt> <v40.txt> <goals.txt>
(the .txt files are antiword/-docx extractions; see the audit log for how they
were produced from the original uploads).
"""
from __future__ import annotations

import re
import sys

APPENDIX_HEADER = (
    "\n\n"
    "======================================================\n"
    "ضمیمه — بخش‌هایی از نسخهٔ قدیمی‌تر (ذخیره‌شده ۰۷/۰۳/۲۰۱۷)\n"
    "که عیناً در نسخهٔ جدیدتر نیامده بود (حفظ کامل، بدون حذف):\n"
    "======================================================\n"
)


def norm(s: str) -> str:
    return re.sub(r"\s+", "", s)


def sentences(text: str) -> list[str]:
    return [s.strip() for s in re.split(r"(?<=[.!؟?])\s+|\n+", text) if s.strip()]


def merge_autobiography(v_new: str, v_old: str) -> tuple[str, int]:
    """Newest revision verbatim + appendix of old-revision blocks not exactly
    present. Returns (merged_body, appendix_block_count)."""
    n_new = norm(v_new)
    missing = [s for s in sentences(v_old) if norm(s) and norm(s) not in n_new]
    body = v_new.strip()
    if missing:
        body += APPENDIX_HEADER + "\n\n".join(missing)
    # ── completeness gate ────────────────────────────────────────────────────
    n_merged = norm(body)
    lost = [s for src in (v_new, v_old) for s in sentences(src)
            if norm(s) and norm(s) not in n_merged]
    if lost:
        print("MERGE GATE FAILED — sentences lost:")
        for s in lost[:10]:
            print("  ", s[:100])
        sys.exit(1)
    return body, len(missing)


def main(v59_path, v40_path, goals_path):
    v59 = open(v59_path, encoding="utf-8").read()
    v40 = open(v40_path, encoding="utf-8").read()
    goals = open(goals_path, encoding="utf-8").read()

    khoda_body, appendix_blocks = merge_autobiography(v59, v40)
    goals_body = goals.strip()
    # goals gate: every paragraph of the source must be present verbatim
    lost = [p for p in goals.split("\n") if p.strip() and p not in goals_body]
    if lost:
        print("GOALS GATE FAILED:", lost[:5])
        sys.exit(1)

    writings = [
        {
            "title": "تاریخچهٔ خداشناسی من (شرح حال و برداشت‌های شخصی)",
            "category": "خداشناسی و شرح حال",
            "body": khoda_body,
            "source_note": (
                "ادغام ۳ فایل Word: دو فایل ۱۴/۰۳/۲۰۱۷ بایت‌به‌بایت یکسان بودند (نسخهٔ ۵۹، "
                "ذخیرهٔ ۰۴/۰۴/۲۰۱۷ — متن پایه)؛ نسخهٔ قدیمی‌تر (۴۰، ذخیرهٔ ۰۷/۰۳/۲۰۱۷) "
                f"{appendix_blocks} بخشِ عیناً-تکرارنشده داشت که در ضمیمهٔ انتهای متن حفظ شد."
            )[:500],
            "written_at": "2017-04-04",
            "sort_order": 0,
        },
        {
            "title": "برنامه‌ریزی برای دنیا و آخرت من (اهداف و فلسفهٔ هرکدام)",
            "category": "برنامه‌ریزی الهی",
            "body": goals_body,
            "source_note": (
                "فایل Word «برنامه‌ریزی دنیا و آخرت» — کامل و دست‌نخورده (ایجاد ۲۰۲۰/۰۹/۰۷، "
                "آخرین ویرایش ۲۰۲۲/۱۱/۰۴). هدف نهایی و اهداف میانی، جبران گذشته، خودسازی، "
                "تشکیلات، مطالعات، برنامه‌های هفتگی و فهرست‌های عشق به خدا/اراده/ترس‌ها/مرد الهی."
            )[:500],
            "written_at": "2022-11-04",
            "sort_order": 1,
        },
    ]

    header = (
        '"""Personal writings seed — GENERATED by scripts/generate_writings_seed.py\n'
        "from the owner's Word documents. Do not hand-edit. The merge gate proved\n"
        "every sentence of every source revision is present verbatim in the stored\n"
        'bodies (exact-duplicate-only dedup, per the owner\'s rule)."""\n\n'
    )
    parts = [header,
             f"PW_EXPECTED_COUNT = {len(writings)}\n",
             f"PW_APPENDIX_BLOCKS = {appendix_blocks}\n",
             f"PW_BODY_CHARS = {[len(w['body']) for w in writings]!r}\n\n",
             "PW_WRITINGS = [\n"]
    for w in writings:
        parts.append("    {\n")
        for key in ("title", "category", "source_note", "written_at"):
            parts.append(f"        {key!r}: {w[key]!r},\n")
        parts.append(f"        'sort_order': {w['sort_order']},\n")
        parts.append(f"        'body': {w['body']!r},\n")
        parts.append("    },\n")
    parts.append("]\n")
    out = "app/services/_personal_writings_seed_data.py"
    with open(out, "w", encoding="utf-8") as f:
        f.write("".join(parts))
    print(f"OK → {out}")
    print(f"writings={len(writings)} appendix_blocks={appendix_blocks} "
          f"body_chars={[len(w['body']) for w in writings]}")


if __name__ == "__main__":
    main(*sys.argv[1:4])
